on:
  workflow_dispatch:

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./perfo/monitoring/events.js