name: k6 monitoring qa1-np

on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 10 * * 1-5'  

env:
  PLAYWRIGHT_CSO_PASSWORD: ${{ secrets.PLAYWRIGHT_CSO_PASSWORD }}
  # Proxy en UPPER + lower
  HTTP_PROXY:  http://198.161.14.25:8080
  HTTPS_PROXY: http://198.161.14.25:8080
  # NO_PROXY:    localhost,127.0.0.1,.corp.ads,.oss.ads,.tsl.telus.com,.tmi.telus.com
  TZ: "America/Montreal"

jobs:
  run-test:
    runs-on: danny-examples
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: perfo/monitoring/event.js